services:
  app:
    build: ./app
    container_name: myapp-springboot
    restart: unless-stopped
    expose:
      - "8277"
    environment:
      - JAVA_TOOL_OPTIONS=-Xms512m -Xmx880m -XX:+UseG1GC -Djava.io.tmpdir=/tmp
      - NLS_LANG=JAPANESE_JAPAN.AL32UTF8
      - NLS_NCHAR=AL32UTF8
      - LD_LIBRARY_PATH=/usr/lib/oracle/23/client64/lib
    volumes:
      - /usr/lib/oracle:/usr/lib/oracle:ro,z
      - /etc/odbc.ini:/etc/odbc.ini:ro,z
      - /etc/odbcinst.ini:/etc/odbcinst.ini:ro,z
 
  nginx:
    image: nginx:alpine
    container_name: myapp-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro,z
      - ./certbot/www:/var/www/certbot:ro,z
      - ./certbot/conf:/etc/letsencrypt:ro,z
      # ↓ 追加:ビルドした Vue の dist を配信ディレクトリにマウント
      - ./frontend/dist:/usr/share/nginx/html:ro,z
    depends_on:
      - app

  certbot:
    image: certbot/certbot:latest
    container_name: myapp-certbot
    volumes:
      - ./certbot/www:/var/www/certbot:rw,z
      - ./certbot/conf:/etc/letsencrypt:rw,z
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew --quiet --webroot --webroot-path=/var/www/certbot; sleep 12h & wait $${!}; done"
